- name: Install/Setup Catalouge service
  hosts: mongodb
  become: yes
  tasks:
    - name: Install Node.js repo
      ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash
    