- name: Install/Setup Catalouge service
  hosts: mongodb
  become: yes
  tasks:
    - name: Install Node.js repo
      ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash
      ignore_errors: true

    - name: Install NodeJS
      ansible.builtin.yum:
        name: nodejs
        state: installed
      ignore_errors: true  

    - name: check Roboshop user exist or not
      ansible.builtin.command: id roboshop
      register: output
      ignore_errors: true

    - when: output != 0
      name: Create user roboshop
      ansible.builtin.user:
        name: roboshop

    # ansible.builtin.stat is used to retrieve_file/file_system status information
    - name: check /app directory exist or not
      ansible.builtin.stat:
        path: /app
      register: directory

    - name: create directory
      ansible.builtin.file:
        path: /app
        state: directory
      when: directory.stat.exists == false
    
    - name: Download catalogue artifact
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
        dest: /tmp
    - name: install unzip tool
      ansible.builtin.apt:
        name: unzip
        state: present
    - name: unzip catalogue artifact
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: yes
    - name: install npm tool
      ansible.builtin.apt:
        name: npm
        state: present
    - name: install catalogue artifact
      community.general.npm:
        path: /app

