- name: Install/Setup Catalouge service
  hosts: mongodb
  become: yes
  tasks:
    - name: Install Node.js repo
      ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash
      ignore_errors: true

    - name: Install NodeJS
      ansible.builtin.yum:
        name: nodejs
        state: installed
      ignore_errors: true  

    - name: check Roboshop user exist or not
      ansible.builtin.command: id roboshop
      register: output
      ignore_errors: true

    - when: output != 0
      name: Create user roboshop
      ansible.builtin.user:
        name: roboshop

    # ansible.builtin.stat is used to retrieve_file/file_system status information
    - name: check /app directory exist or not
      ansible.builtin.stat:
        path: /app
      register: directory

    - name: create directory
      ansible.builtin.file:
        path: /app
        state: directory
    - when: directory.stat.exist == false
    
    - name: print to check output
      ansible.builtin.debug:
        msg: "{{directory}}"


    