- name: install/configure mysql
  hosts: mysql
  become: yes
  tasks: 
    - name: install extra packages for enterprise linux
      ansible.builtin.yum:
        name: epel-release
        state: installed

    - name: Temporarily set SELinux to permissive mode
      ansible.builtin.command: setenforce 0

    - name: Remove conflicting mysql/mariadb packages
      ansible.builtin.yum:
        name:
          - mysql
          - mysql-server
          - mysql-libs
          - mysql-common
          - mariadb
          - mariadb-libs
          - mariadb-connector-c-config
        state: absent
        autoremove: yes # Remove any unused dependencies as well
      ignore_errors: yes # Ignore errors if a package is already removed

    - name: disable mysql-8 default module
      ansible.builtin.command: yum module disable mysql -y 

    - name: copy MySQL 5.7 Server 
      ansible.builtin.copy:
        src: 13-mysql.repo
        dest: /etc/yum.repos.d/mysql.repo

    - name: install mysql
      ansible.builtin.command: yum install mysql-community-server -y
    
    - name: enable/start mysql
      ansible.builtin.service:
        name: mysqld
        enabled: true
        state: restarted

    - name: change the default root password in order to start using the database service
      ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1

    