- name: install/configure mysql
  hosts: mysql
  become: yes
  tasks: 
    - name: disable mysql-8 default module
      ansible.builtin.yum:
        name: mysql
        disablerepo: "mysql"
    
    - name: copy mysql repo
      ansible.builtin.copy:
        src: 13-mysql.repo
        dest: /etc/yum.repos.d/mysql.repo
    
    - name: install mysql 
      ansible.builtin.yum:
        name: mysql-community-server
        state: installed

    - name: enable/start mysql
      ansible.builtin.service:
        name: mysqld
        enabled: true
        state: restarted

    