---
- name: Install and Configure Shipping Service
  hosts: shipping
  become: yes
  vars:
    mysql_host: 172.31.15.68
    cart_host: 172.31.8.30 # <-- IMPORTANT: Update this IP/DNS name

  pre_tasks:
    - name: Ensure Python 3 is installed
      ansible.builtin.raw: yum install -y python3
      changed_when: false
      ignore_errors: true

  tasks:
    - name: Install prerequisite packages
      ansible.builtin.yum:
        name:
          - epel-release
          - maven
          - mysql
          - python3-PyMySQL
        state: present

    - name: Create Roboshop application user
      ansible.builtin.user:
        name: roboshop
        system: yes
        state: present

    - name: Ensure /app directory exists
      ansible.builtin.file:
        path: /app
        state: directory
        owner: roboshop
        group: roboshop

    - name: Download and unpack shipping artifact
      ansible.builtin.unarchive:
        src: https://roboshop-builds.s3.amazonaws.com/shipping.zip
        dest: /app
        remote_src: yes
        owner: roboshop
        group: roboshop

    - name: Build application with Maven
      ansible.builtin.command: mvn clean package
      args:
        chdir: /app

    - name: Create shipping systemd service file
      ansible.builtin.copy:
        dest: /etc/systemd/system/shipping.service
        content: |
          [Unit]
          Description=Shipping Service

          [Service]
          User=roboshop
          Environment="CART_ENDPOINT={{ cart_host }}:8080"
          Environment="DB_HOST={{ mysql_host }}"
          Environment="DB_USER=roboshop"
          Environment="DB_PASS=RoboShop@1"
          ExecStart=/usr/bin/java -jar /app/target/shipping-1.0.jar
          SyslogIdentifier=shipping

          [Install]
          WantedBy=multi-user.target
      # This tells Ansible to run the handler if this task makes a change.
      notify: Reload and restart shipping

    # --- Database Schema Correction Block (using the simple, forceful method) ---

    - name: Load the initial schema into MySQL
      ansible.builtin.shell: "mysql -h {{ mysql_host }} -uroboshop -pRoboShop@1 < /app/db/schema.sql"
      changed_when: false
      ignore_errors: true

    - name: Create the 'shipping' database
      community.mysql.mysql_db:
        name: shipping
        state: present
        login_user: roboshop
        login_password: "RoboShop@1"
        login_host: "{{ mysql_host }}"

    - name: Rename the table from 'cities' DB to 'shipping' DB
      community.mysql.mysql_query:
        login_user: roboshop
        login_password: "RoboShop@1"
        login_host: "{{ mysql_host }}"
        query: "RENAME TABLE cities.cities TO shipping.cities;"
      ignore_errors: true

    - name: Drop the old 'cities' database
      community.mysql.mysql_db:
        name: cities
        state: absent
        login_user: roboshop
        login_password: "RoboShop@1"
        login_host: "{{ mysql_host }}"
      ignore_errors: true

    - name: Rename table inside 'shipping' DB to 'shipping_details'
      community.mysql.mysql_query:
        login_user: roboshop
        login_password: "RoboShop@1"
        login_host: "{{ mysql_host }}"
        login_db: shipping
        query: "RENAME TABLE cities TO shipping_details;"
      ignore_errors: true
    
    - name: Create the 'shipping' application user for the Shipping service
      community.mysql.mysql_user:
        name: shipping # The exact username the application requires
        host: '%'     # Allow connection from any host in your private network
        password: "RoboShop@1" # You can use the same password for simplicity
        priv: 'shipping.*:ALL' # Grant ALL privileges ON the 'shipping' database TO this user
        state: present
        login_user: root
        login_password: "RoboShop@1"

  # --- HANDLERS BLOCK (This was the missing piece) ---
  # Handlers are only run at the end of the play if they have been notified.
  handlers:
    - name: Reload and restart shipping
      ansible.builtin.systemd:
        name: shipping
        daemon_reload: yes
        state: restarted
        enabled: yes