- name: installing rabbitmq
  hosts: rabbitmq
  become: yes
  tasks:
    - name: downoad rabbitmq repo
      ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash
    
    - name: Configure YUM Repos for RabbitMQ.
      ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

    - name: installing rabbitmq
      ansible.builtin.yum:
        name: rabbitmq-server
        state: installed
    
    - name: start/enable rabbitmq
      ansible.builtin.service:
        name: rabbitmq-server
        state: restarted
        enabled: true

    - name: create user for the application.
      ansible.builtin.command: rabbitmqctl add_user roboshop roboshop123

    - name: set_permissions rabbitmq
      ansible.builtin.command: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"