- name: web server
  hosts: web
  become: yes
  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: "nginx"
        state: "present"
    - name: start nginx
      ansible.builtin.service:
        name: "nginx"
        state: "started"
    - name: remove nginx default files
      ansible.builtin.command: rm -rf /var/www/html/*
    - name: install frontend content
      ansible.builtin.command: curl -o /tmp/web.zip https://roboshop-builds.s3.amazonaws.com/web.zip
      ansible.builtin.command: cd /var/www/html
      ansible.builtin.command: unzip /tmp/web.zip